import { useState } from 'react';
import { soundManager } from '../utils/sounds';
import './DiceRoll.css';

export const DiceRoll = () => {
    const [result, setResult] = useState<number | null>(6); // Show 6 by default
    const [isRolling, setIsRolling] = useState(false);

    const rollDice = () => {
        if (isRolling) return;

        setIsRolling(true);
        soundManager.playDiceRoll(); // Realistic dice rolling sound

        // Animate rolling
        let count = 0;
        const interval = setInterval(() => {
            setResult(Math.floor(Math.random() * 6) + 1);
            count++;
            if (count >= 15) {
                clearInterval(interval);
                const finalResult = Math.floor(Math.random() * 6) + 1;
                setResult(finalResult);
                soundManager.playDiceLand(); // Realistic dice landing sound
                setIsRolling(false);
            }
        }, 100);
    };

    const getTransformFor = (num: number) => {
        // Rotations to bring the target face to the FRONT
        switch (num) {
            case 1: return 'rotateX(0deg) rotateY(0deg)';
            case 2: return 'rotateX(0deg) rotateY(-90deg)';
            case 3: return 'rotateX(0deg) rotateY(-180deg)'; // Adjusted for layout
            case 4: return 'rotateX(0deg) rotateY(90deg)';
            case 5: return 'rotateX(-90deg) rotateY(0deg)';
            case 6: return 'rotateX(90deg) rotateY(0deg)';
            default: return 'rotateX(0deg) rotateY(0deg)';
        }
    };

    const getDotPositions = (num: number) => {
        const positions: number[][] = [];
        switch (num) {
            case 1:
                positions.push([50, 50]);
                break;
            case 2:
                positions.push([25, 25], [75, 75]);
                break;
            case 3:
                positions.push([25, 25], [50, 50], [75, 75]);
                break;
            case 4:
                positions.push([25, 25], [75, 25], [25, 75], [75, 75]);
                break;
            case 5:
                positions.push([25, 25], [75, 25], [50, 50], [25, 75], [75, 75]);
                break;
            case 6:
                positions.push([25, 20], [75, 20], [25, 50], [75, 50], [25, 80], [75, 80]);
                break;
        }
        return positions;
    };

    return (
        <div className="dice-roll-container">
            <div className="dice-scene">
                <div
                    className={`dice-cube ${isRolling ? 'rolling' : ''}`}
                    style={{
                        transform: !isRolling && result ? getTransformFor(result) : ''
                    }}
                >
                    {[1, 2, 3, 4, 5, 6].map(num => (
                        <div key={num} className={`cube-face face-${num}`}>
                            {getDotPositions(num).map((pos, i) => (
                                <div
                                    key={i}
                                    className="dice-dot"
                                    style={{ left: `${pos[0]}%`, top: `${pos[1]}%` }}
                                />
                            ))}
                        </div>
                    ))}
                </div>
            </div>

            <div className="dice-controls">
                <button
                    className="btn btn-primary btn-lg"
                    onClick={rollDice}
                    disabled={isRolling}
                >
                    {isRolling ? '🎲 Rolling...' : '🎲 Roll Dice'}
                </button>
            </div>

            {result !== null && !isRolling && (
                <div className="result-display fade-in">
                    <h2 className="result-text">You rolled a {result}</h2>
                    <p style={{ fontSize: '0.8rem', color: 'var(--text-tertiary)', marginTop: '10px' }}>
                        Disclaimer: Result is fully autogenerated for entertainment only.
                    </p>
                </div>
            )}

            <div className="info-section">
                <p className="info-text">
                    💡 Roll a standard 6-sided dice. Each number from 1 to 6 has an equal chance of appearing.
                </p>
            </div>
        </div>
    );
};
