import { useState } from 'react';
import { soundManager } from '../utils/sounds';
import './RandomNumber.css';

export const RandomNumber = () => {
    const [min, setMin] = useState<string>('1');
    const [max, setMax] = useState<string>('100');
    const [result, setResult] = useState<number | null>(null);
    const [isGenerating, setIsGenerating] = useState(false);
    const [error, setError] = useState<string>('');

    const generateNumber = () => {
        const minNum = parseInt(min);
        const maxNum = parseInt(max);

        // Validation
        if (isNaN(minNum) || isNaN(maxNum)) {
            setError('Please enter valid numbers');
            return;
        }

        if (minNum >= maxNum) {
            setError('Min must be less than Max');
            return;
        }

        if (maxNum - minNum > 1000000) {
            setError('Range too large (max 1,000,000)');
            return;
        }

        setError('');
        setIsGenerating(true);
        soundManager.playNumberGenerate(); // Realistic number generation sound

        // Animate number generation
        let count = 0;
        const interval = setInterval(() => {
            const randomNum = Math.floor(Math.random() * (maxNum - minNum + 1)) + minNum;
            setResult(randomNum);
            count++;

            if (count >= 20) {
                clearInterval(interval);
                const finalResult = Math.floor(Math.random() * (maxNum - minNum + 1)) + minNum;
                setResult(finalResult);
                soundManager.playNumberReveal(); // Realistic number reveal sound
                setIsGenerating(false);
            }
        }, 50);
    };

    const handleKeyPress = (e: React.KeyboardEvent) => {
        if (e.key === 'Enter' && !isGenerating) {
            generateNumber();
        }
    };

    return (
        <div className="random-number-container">
            <div className="number-inputs">
                <div className="input-group">
                    <label htmlFor="min">Minimum</label>
                    <input
                        id="min"
                        type="number"
                        value={min}
                        onChange={(e) => setMin(e.target.value)}
                        onKeyPress={handleKeyPress}
                        disabled={isGenerating}
                    />
                </div>

                <div className="input-separator">to</div>

                <div className="input-group">
                    <label htmlFor="max">Maximum</label>
                    <input
                        id="max"
                        type="number"
                        value={max}
                        onChange={(e) => setMax(e.target.value)}
                        onKeyPress={handleKeyPress}
                        disabled={isGenerating}
                    />
                </div>
            </div>

            {error && (
                <div className="error-message">
                    ⚠️ {error}
                </div>
            )}

            <div className="number-controls">
                <button
                    className="btn btn-primary btn-lg"
                    onClick={generateNumber}
                    disabled={isGenerating}
                >
                    {isGenerating ? '🔢 Generating...' : '🔢 Generate Number'}
                </button>
            </div>

            {result !== null && (
                <div className="result-display fade-in">
                    <h2 className={`result-text number-result ${isGenerating ? 'animating' : ''}`}>
                        {result.toLocaleString()}
                    </h2>
                    <p style={{ fontSize: '0.8rem', color: 'var(--text-tertiary)', marginTop: '10px' }}>
                        Disclaimer: Result is fully autogenerated for entertainment only.
                    </p>
                    <p>Random number between {min} and {max}</p>
                </div>
            )}

            <div className="info-section">
                <p className="info-text">
                    💡 Generate a random number within your specified range. Perfect for raffles, games, or making numerical decisions.
                </p>
            </div>

            <div className="quick-presets">
                <h4>Quick Presets</h4>
                <div className="preset-buttons">
                    <button
                        className="preset-btn"
                        onClick={() => { setMin('1'); setMax('10'); }}
                    >
                        1-10
                    </button>
                    <button
                        className="preset-btn"
                        onClick={() => { setMin('1'); setMax('100'); }}
                    >
                        1-100
                    </button>
                    <button
                        className="preset-btn"
                        onClick={() => { setMin('1'); setMax('1000'); }}
                    >
                        1-1000
                    </button>
                    <button
                        className="preset-btn"
                        onClick={() => { setMin('0'); setMax('1'); }}
                    >
                        0-1
                    </button>
                </div>
            </div>
        </div>
    );
};
