import { useState } from 'react';
import { soundManager } from '../utils/sounds';
import './YesNo.css';

export const YesNo = () => {
    const [result, setResult] = useState<'yes' | 'no' | null>(null);
    const [isDeciding, setIsDeciding] = useState(false);

    const makeDecision = () => {
        if (isDeciding) return;

        setIsDeciding(true);
        setResult(null);
        soundManager.playDecisionMaking(); // Realistic decision-making sound

        // Animate decision making
        setTimeout(() => {
            const decision: 'yes' | 'no' = Math.random() < 0.5 ? 'yes' : 'no';
            setResult(decision);
            soundManager.playDecisionReveal(decision === 'yes'); // Different sound for yes vs no
            setIsDeciding(false);
        }, 1500);
    };

    return (
        <div className="yes-no-container">
            <div className="decision-display">
                {isDeciding ? (
                    <div className="deciding-animation">
                        <div className="decision-option yes pulsing">YES</div>
                        <div className="decision-option no pulsing">NO</div>
                    </div>
                ) : result ? (
                    <div className={`decision-result ${result} fade-in`}>
                        <div className="result-icon">
                            {result === 'yes' ? '✅' : '❌'}
                        </div>
                        <div className="result-label">
                            {result === 'yes' ? 'YES' : 'NO'}
                        </div>
                        <p style={{ fontSize: '0.8rem', color: 'var(--text-tertiary)', marginTop: '10px' }}>
                            Disclaimer: Result is fully autogenerated for entertainment only.
                        </p>
                    </div>
                ) : (
                    <div className="decision-placeholder">
                        <div className="placeholder-icon">❓</div>
                        <div className="placeholder-text">Ready to decide?</div>
                    </div>
                )}
            </div>

            <div className="yes-no-controls">
                <button
                    className="btn btn-primary btn-lg"
                    onClick={makeDecision}
                    disabled={isDeciding}
                >
                    {isDeciding ? '🤔 Deciding...' : '❓ Yes or No?'}
                </button>
            </div>

            {result && !isDeciding && (
                <div className="result-message fade-in">
                    <p className={result === 'yes' ? 'affirmative' : 'negative'}>
                        {result === 'yes'
                            ? '✨ The answer is YES! Go for it!'
                            : '🛑 The answer is NO. Maybe try something else?'}
                    </p>
                </div>
            )}

            <div className="info-section">
                <p className="info-text">
                    💡 Let fate decide with a simple Yes or No answer. Perfect for quick binary decisions when you're stuck between two choices.
                </p>
            </div>

            <div className="suggestions-section">
                <h4>Great for deciding:</h4>
                <ul className="suggestion-list">
                    <li>Should I go out tonight?</li>
                    <li>Is it time for a break?</li>
                    <li>Should I try something new?</li>
                    <li>Do I really need this?</li>
                    <li>Should I take the risk?</li>
                </ul>
            </div>
        </div>
    );
};
