import { SEO } from '../components/SEO';
import './LegalPage.css';

export const DisclaimerPage = () => {
    return (
        <div className="legal-page">
            <SEO
                title="Disclaimer | Decision Helper"
                description="Disclaimer for Decision Helper decision-making tools"
            />

            <div className="container">
                <div className="legal-content">
                    <h1>Disclaimer</h1>
                    <p className="last-updated">Last updated: January 2, 2026</p>

                    <section>
                        <h2>1. General Information</h2>
                        <p>
                            Decision Helper provides random decision-making tools for entertainment and general use purposes only. The results generated by our tools should not be relied upon for critical, legal, medical, financial, or life-altering decisions.
                        </p>
                    </section>

                    <section>
                        <h2>2. Randomness</h2>
                        <p>
                            All our tools use JavaScript's Math.random() function to generate results. While this provides pseudo-random results suitable for general purposes, it should not be used for cryptographic or security purposes.
                        </p>
                    </section>

                    <section>
                        <h2>3. No Guarantee</h2>
                        <p>
                            We make no guarantees about the fairness, accuracy, or appropriateness of the results generated by our tools. Users are responsible for their own decisions.
                        </p>
                    </section>

                    <section>
                        <h2>4. Use at Your Own Risk</h2>
                        <p>
                            This service is provided "as is" without any warranties of any kind. By using this website, you acknowledge that you use these tools at your own risk.
                        </p>
                    </section>

                    <section>
                        <h2>5. Not Professional Advice</h2>
                        <p>
                            Decision Helper does not provide professional advice of any kind. Results from our tools should not replace professional judgment, advice, or consultation.
                        </p>
                    </section>

                    <section>
                        <h2>6. Limitation of Liability</h2>
                        <p>
                            In no event shall Decision Helper be liable for any damages arising from the use or inability to use this service.
                        </p>
                    </section>

                    <section>
                        <h2>7. Contact</h2>
                        <p>
                            If you have questions about this disclaimer, please visit our <a href="/contact">Contact page</a>.
                        </p>
                    </section>
                </div>
            </div>
        </div>
    );
};
